-- Core feedback table
CREATE TABLE IF NOT EXISTS feedback (
    id              TEXT PRIMARY KEY,          -- UUID
    source          TEXT NOT NULL,             -- appstore | playstore | spotify_community | trustpilot
    source_id       TEXT NOT NULL,             -- Original ID from the source platform
    country         TEXT,                      -- 'US', 'GB', 'IN', etc. (for app stores)
    author          TEXT,
    content         TEXT NOT NULL,
    url             TEXT,
    posted_at       TIMESTAMP,
    collected_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    classified_at   TIMESTAMP,
    skipped         BOOLEAN DEFAULT 0,         -- 1 = model returned off-topic/all-null; retained for audit, excluded from clustering
    raw_json        TEXT,                      -- Original API response stored for auditability
    UNIQUE(source, source_id)                  -- Prevents duplicate ingestion
);

-- AI classification results (1:1 with feedback)
CREATE TABLE IF NOT EXISTS classifications (
    feedback_id             TEXT PRIMARY KEY REFERENCES feedback(id),
    topic                   TEXT,                           -- open text: what the review is about
    core_complaint          TEXT,                           -- open text: main grievance, or NULL if positive
    trust_level             TEXT CHECK(trust_level IN ('high','medium','low','broken')),
    sentiment               TEXT CHECK(sentiment IN ('positive','negative','mixed','neutral')),
    frustration_intensity   TEXT CHECK(frustration_intensity IN ('mild','moderate','severe','churned')),
    user_job_to_be_done     TEXT,
    repeat_listen_reason    TEXT,                           -- open text: why user repeats, or NULL
    workaround_mentioned    BOOLEAN DEFAULT 0,
    workaround_description  TEXT,
    behaviour_pattern       TEXT,                           -- open text: model describes user behaviour
    pattern_evidence        TEXT,                           -- one sentence from source text
    quote_translated        TEXT,                           -- English translation of pattern_evidence
    unmet_need              TEXT,
    classified_at           TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Collection run log (tracks daily runs for incremental collection)
CREATE TABLE IF NOT EXISTS collection_runs (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    source          TEXT NOT NULL,
    started_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    completed_at    TIMESTAMP,
    records_fetched INTEGER DEFAULT 0,
    records_new     INTEGER DEFAULT 0,
    status          TEXT CHECK(status IN ('running','success','failed')),
    error_message   TEXT
);

-- Daily delta summaries (auto-generated after each nightly run)
CREATE TABLE IF NOT EXISTS daily_summaries (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    summary_date    DATE NOT NULL UNIQUE,
    total_new       INTEGER,
    by_source       TEXT,              -- JSON: {"appstore": 12, "playstore": 5, "trustpilot": 2}
    by_topic        TEXT,              -- JSON: open-text tallied, e.g. {"Discover Weekly feels stale": 8, "shuffle keeps repeating": 5, ...}
    top_complaints  TEXT,              -- JSON array of top 5 core_complaint values (illustrative only — values are open text, not a fixed list)
    growing_patterns TEXT,             -- JSON array of patterns trending up
    fading_patterns  TEXT,             -- JSON array of patterns trending down
    generated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Theme clusters (emergent, not predefined — populated by Phase 4.5 clustering engine)
CREATE TABLE IF NOT EXISTS theme_clusters (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    cluster_type    TEXT NOT NULL,             -- 'topic' | 'complaint' | 'behaviour' | 'unmet_need'
    label           TEXT NOT NULL,             -- auto-generated by Groq from cluster members
    member_count    INTEGER NOT NULL,
    percentage      REAL NOT NULL,             -- % of total classified reviews
    representative_quotes TEXT,                -- JSON array of 3-5 verified verbatim quotes
    sources_breakdown TEXT,                    -- JSON: {"appstore": 12, "playstore": 5, ...}
    countries_breakdown TEXT,                  -- JSON: {"US": 8, "GB": 4, ...}
    member_ids      TEXT,                      -- JSON array of feedback_ids in this cluster
    clustered_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    run_id          INTEGER                    -- links to clustering_runs.id
);

-- Clustering run log (tracks each batch clustering execution)
CREATE TABLE IF NOT EXISTS clustering_runs (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    started_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    completed_at    TIMESTAMP,
    total_records   INTEGER,
    clusters_found  INTEGER,
    cluster_types   TEXT,                      -- JSON array of types clustered
    status          TEXT CHECK(status IN ('running','success','failed')),
    error_message   TEXT
);

-- Indexes for dashboard query performance
CREATE INDEX IF NOT EXISTS idx_feedback_source ON feedback(source);
CREATE INDEX IF NOT EXISTS idx_feedback_posted ON feedback(posted_at);
CREATE INDEX IF NOT EXISTS idx_feedback_skipped ON feedback(skipped);
CREATE INDEX IF NOT EXISTS idx_class_topic ON classifications(topic);
CREATE INDEX IF NOT EXISTS idx_class_sentiment ON classifications(sentiment);
CREATE INDEX IF NOT EXISTS idx_class_intensity ON classifications(frustration_intensity);
CREATE INDEX IF NOT EXISTS idx_class_behaviour ON classifications(behaviour_pattern);
CREATE INDEX IF NOT EXISTS idx_theme_type ON theme_clusters(cluster_type);
CREATE INDEX IF NOT EXISTS idx_theme_run ON theme_clusters(run_id);
